@MyLibrary_HostAddress = https://localhost:7296

###

# All books with version 1.0 Url
GET {{MyLibrary_HostAddress}}/api/v1/Book

###

# One book with version 1.0 Url
GET {{MyLibrary_HostAddress}}/api/v1/Book/1

###


# All books with version 2.0 Url
GET {{MyLibrary_HostAddress}}/api/v2/Book

###

# One book with version 2.0 Url
GET {{MyLibrary_HostAddress}}/api/v2/Book/1

###

# All authors with version 2.0 Url
GET {{MyLibrary_HostAddress}}/api/v2/Author

###

# All books for an author with version 2.0 Url

GET {{MyLibrary_HostAddress}}/api/v2/Author/Ernest%20Hemingway/Books


### 

# All Categories with version 2.0 Url

GET {{MyLibrary_HostAddress}}/api/v2/Category

###

# All books for a category with version 2.0 Url

GET {{MyLibrary_HostAddress}}/api/v2/Category/Fantasy/Books